services:
  db:
    image: postgres:16.1
    container_name: go-db
    restart: always
    shm_size: 1024MB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=development
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: >
      -c work_mem=128MB
      -c logging_collector=on
      -c log_statement=all
      -c log_duration=1
      -c log_connections=1
      -c log_filename=%Y-%b-%d_%H:%M:%S.log

volumes:
  pgdata:
